"""adiciona unique constraint para dedup de leituras

Revision ID: 0a1560429f38
Revises: 23a94416264a
Create Date: 2026-09-22 22:16:52.982062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1560429f38'
down_revision: Union[str, Sequence[str], None] = '23a94416264a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_leituras_sensor_ts', 'leituras', ['id_sensor', 'ts'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_leituras_sensor_ts', 'leituras', type_='unique')
    # ### end Alembic commands ###
